name: Build RuleSet

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate RuleSets
        run: |
          mkdir -p rules

          for file in source/*.txt
          do
            name=$(basename "$file" .txt)

            cat "$file" \
            | grep -v '^#' \
            | sed '/^$/d' \
            | sort -u \
            | awk '
              {
                if ($0 ~ /,/)
                  print $0;
                else
                  print "DOMAIN-SUFFIX,"$0
              }
            ' \
            > "rules/${name}.list"

            echo "Generated rules/${name}.list"
          done

          cd rules
          sha256sum *.list > checksums.txt

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add rules

          git diff --staged --quiet || \
          git commit -m "Auto Update Rules"
      - name: Push
  run: |
    git pull --rebase origin main
    git push origin main